name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v3
      - use: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v3
      - use: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v3
      - use: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test